swagger.yamlの改修
traPtitech/anke-to pull request #1140
Opened 2023-12-06 04:37 UTC by reiroop

2023-12-10 10:25 UTC, cp-20 requested changes

2023-12-10 10:25 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +      description: あるresponseIDを持つ回答に含まれる全ての質問に対する自分の回答を取得します。
```suggestion
      description: 回答を取得します。
```

2023-12-10 10:25 UTC, cp-20 commented on docs/swagger/swagger.yaml
>            description: アンケートの回答の期限がきれたため回答が存在しません
```suggestion
          description: 回答が存在しません
```

2023-12-10 10:25 UTC, cp-20 commented on docs/swagger/swagger.yaml
>            description: responseIDを取得できませんでした
```suggestion
          description: 回答を正常に取得できませんでした
```

2023-12-10 10:25 UTC, cp-20 commented on docs/swagger/swagger.yaml
>        operationId: getResponses
```suggestion
      operationId: getResponse
```

2023-12-10 10:25 UTC, cp-20 commented on docs/swagger/swagger.yaml
>        description: 回答を変更します．
```suggestion
      description: 回答を変更します。
```

2023-12-10 10:25 UTC, cp-20 commented on docs/swagger/swagger.yaml
>            description: 正常に回答を変更できました．
```suggestion
          description: 正常に回答を変更できました
```

2023-12-10 10:25 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +          description: 回答を変更する権限がありません。
```suggestion
          description: 回答を変更する権限がありません
```

2023-12-10 10:25 UTC, cp-20 commented on docs/swagger/swagger.yaml
>        description: 回答を削除します．
```suggestion
      description: 回答を削除します
```

2023-12-10 10:25 UTC, cp-20 commented on docs/swagger/swagger.yaml
>            description: 正常に回答を削除できました．
```suggestion
          description: 正常に回答を削除できました
```

2023-12-10 10:25 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +          description: 正常に回答を作成できました．作成された回答を返します．
```suggestion
          description: 正常に回答を作成できました。作成された回答を返します。
```

2023-12-10 10:25 UTC, cp-20 commented on docs/swagger/swagger.yaml
>            description: 正常に取得できました．ユーザーの配列を返します．
```suggestion
          description: 正常に取得できました。ユーザーの配列を返します。
```

2023-12-10 10:25 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +        "500":
ここの説明間違ってそうです

2023-12-10 10:25 UTC, cp-20 commented on docs/swagger/swagger.yaml
>            description: questionnaireIDの型が数値ではありません
```suggestion
          description: questionnaireIDが無効です
```

2023-12-10 10:25 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +                  $ref: "#/components/schemas/Responses"
```suggestion
                $ref: "#/components/schemas/Responses"
```

2023-12-10 10:25 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +                  $ref: "#/components/schemas/Response"
```suggestion
                $ref: "#/components/schemas/Responses"
```

2023-12-10 10:25 UTC, cp-20 commented on docs/swagger/swagger.yaml
>        description: 自分が対象になっている アンケートのリストを取得します。
```suggestion
      description: 自分が対象になっているアンケートのリストを取得します。
```

2023-12-10 10:25 UTC, cp-20 commented on docs/swagger/swagger.yaml
>      get:
この下の`getTargetedQuestionnaire`は`getTargetedQuestionnaires` (複数形) な気がします

2023-12-10 10:25 UTC, cp-20 commented on docs/swagger/swagger.yaml
>            description: 回答のリストを取得できませんでした
これもエラーとして微妙な気がします

2023-12-10 10:25 UTC, cp-20 commented on docs/swagger/swagger.yaml
>        description: 自分が対象になっている アンケートのリストを取得します。
```suggestion
      description: あるユーザーが対象になっているアンケートのリストを取得します。
```

2023-12-10 10:25 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +                  $ref: "#/components/schemas/QuestionnaireList"
```suggestion
                $ref: "#/components/schemas/QuestionnaireList"
```

2023-12-10 10:33 UTC, reiroop commented on docs/swagger/swagger.yaml
> +          description: アンケートの回答の期限がきれたため回答が存在しません
もとからあったのをそのままにしてます！

2023-12-10 10:33 UTC, reiroop commented on docs/swagger/swagger.yaml
>            description: responseIDが数値に変換できませんでした
修正しました

2023-12-10 10:34 UTC, reiroop commented on docs/swagger/swagger.yaml
>        operationId: getResponses
修正しました

2023-12-10 10:36 UTC, reiroop commented on docs/swagger/swagger.yaml
> +  /questionnaires/{questionnaireID}/result:
/questionnaires/{questionnaireID}/responsesのレスポンスを処理すればいいかなーと思ってここを匿名用にしました、専用のAPIが必要ならそれも書きます

2023-12-10 10:38 UTC, reiroop commented on docs/swagger/swagger.yaml
> +        - $ref: "#/components/schemas/QuestionnaireIsPublished"
自分が管理しているアンケート的な絞り方でも使うことを想定しているので入れてます！

2023-12-10 10:39 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +          description: アンケートの回答の期限がきれたため回答が存在しません
なら404はそもそもアンケートが見つからないみたいな感じに変えて欲しいです

2023-12-10 10:39 UTC, reiroop commented on docs/swagger/swagger.yaml
>          自分がターゲットになっていないもののみ取得 (true), ターゲットになっているものも含めてすべて取得 (false)。デフォルトはfalse。
修正しました

2023-12-10 10:39 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +          description: 回答期限が過ぎたため回答できません
422あたりが適切なステータスコードかもです。 (405はMethod Not Allowedなのでなんか違うかも)

ref: https://developer.mozilla.org/ja/docs/Web/HTTP/Status/422

2023-12-10 10:40 UTC, reiroop commented on docs/swagger/swagger.yaml
>        description: 回答を変更します．
修正しました

2023-12-10 10:40 UTC, reiroop commented on docs/swagger/swagger.yaml
>            description: アンケートの回答の期限がきれたため回答が存在しません
修正しました

2023-12-10 10:40 UTC, reiroop commented on docs/swagger/swagger.yaml
>            description: responseIDを取得できませんでした
修正しました

2023-12-10 10:40 UTC, reiroop commented on docs/swagger/swagger.yaml
> +      description: あるresponseIDを持つ回答に含まれる全ての質問に対する自分の回答を取得します。
修正しました

2023-12-10 10:42 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +  /questionnaires/{questionnaireID}/result:
しっかり分かってるなら大丈夫です！良さそうです！

2023-12-10 10:43 UTC, reiroop commented on docs/swagger/swagger.yaml
> +          description: 回答期限が過ぎたため回答できません
了解です

2023-12-10 10:44 UTC, reiroop commented on docs/swagger/swagger.yaml
>            description: 正常に回答を削除できました．
修正しました

2023-12-10 10:44 UTC, reiroop commented on docs/swagger/swagger.yaml
>        description: 回答を削除します．
修正しました

2023-12-10 10:44 UTC, reiroop commented on docs/swagger/swagger.yaml
> +          description: 正常に回答を作成できました．作成された回答を返します．
修正しました

2023-12-10 10:44 UTC, reiroop commented on docs/swagger/swagger.yaml
>            description: 正常に回答を変更できました．
修正しました

2023-12-10 10:45 UTC, reiroop commented on docs/swagger/swagger.yaml
> +          description: 回答を変更する権限がありません。
修正しました

2023-12-10 10:45 UTC, cp-20 commented on .vscode/settings.json
単に`.gitignore`に入れるだけだと消えないので`git rm -rf .vscode/settings.json`してほしいです

2023-12-10 10:49 UTC, reiroop commented on .vscode/settings.json
しました！

2023-12-10 10:57 UTC, reiroop commented on docs/swagger/swagger.yaml
> +        $ref: "#/components/schemas/QuestionnaireSummary"
完全にミスです！直しました

2023-12-10 11:20 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +paths: #TODO: tagの整理
TODOは消してもよさそう
```suggestion
paths:
```

2023-12-10 11:21 UTC, reiroop commented on docs/swagger/swagger.yaml
>        responses:
直しました！

2023-12-10 11:28 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +      oneOf:
Resultが返すべきはResponseBodyの配列ではない気がします。ResponseBodyは現状1つの質問に対する答え (ただしどのアンケートのどの質問かはわからない) しか持っていないので、これだけだと集計できない気がします

2023-12-10 11:33 UTC, reiroop commented on docs/swagger/swagger.yaml
> +      oneOf:
ミスですね、ありがとうございます

2023-12-10 11:37 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +        description: |
ref: https://zenn.dev/link/comments/962eed85714c8e

```suggestion
          authorizationUrl: "https://q.trap.jp/api/v3/oauth2/authorize"
          tokenUrl: "https://q.trap.jp/api/v3/oauth2/token"
```

2023-12-10 11:39 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +        example: cp20
```suggestion
        type: string
        format: uuid
        example: 13554284-bd77-483c-ab89-38618a8812af
```

2023-12-10 11:40 UTC, cp-20 commented on docs/swagger/swagger.yaml
>        type: object
```suggestion
          type: array
          items:
            type: number
```

2023-12-10 11:40 UTC, cp-20 commented on docs/swagger/swagger.yaml
>        type: object
```suggestion
          type: number
```

2023-12-10 11:41 UTC, cp-20 commented on docs/swagger/swagger.yaml
>        type: object
```suggestion
          type: number
```

2023-12-10 11:45 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +              type: number
これが他のResultSettings~~~と違うので修正してもらえると助かります

2023-12-10 11:46 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +        - $ref: "#/components/schemas/ResponseSettingsScale"
```suggestion
    ResultBody:
      oneOf:
        - $ref: "#/components/schemas/ResultSettingsText"
        - $ref: "#/components/schemas/ResultSettingsTextLong"
        - $ref: "#/components/schemas/ResultSettingsNumber"
        - $ref: "#/components/schemas/ResultSettingsSingleChoice"
        - $ref: "#/components/schemas/ResultSettingsMultipleChoice"
        - $ref: "#/components/schemas/ResultSettingsScale"
```

2023-12-10 11:47 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +        responseNum:
回答の合計数を指してるなら修正して欲しいです

```suggestion
        responseCount:
```

2023-12-10 11:48 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +        answerIndexes:
ここだけanswerがついてるのが違和感がありますね～　全部に付けるかこれを外すかしてほしいかもです

2023-12-10 11:48 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +        answerIndexes:
ここだけanswerがついてるのが違和感がありますね～　全部に付けるかこれを外すかしてほしいかもです (Responseと同じ)

2023-12-10 11:54 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +            type: string
```suggestion
    QuestionSettingsMultipleChoice:
      type: object
      properties:
        options:
          type: array
          items:
            type: string
      required:
        - options
```

2023-12-10 11:55 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +            type: string
```suggestion
    QuestionSettingsSingleChoice:
      type: object
      properties:
        options:
          type: array
          items:
            type: string
      required:
        - options
```

2023-12-10 12:01 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +          $ref: "#/components/schemas/QuestionType"
QuestionTypeはそれぞれのQuestionSettings~~~に持たせた方が厳密になりますね

2023-12-10 12:03 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +        - responded_at
どこでも使われてないですね　いらないなら削除してもいい気がします
```suggestion
```

2023-12-10 12:06 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +            回答必須でない場合、またはすべてのターゲットが回答済みの場合、true を返す。それ以外はfalseを返す。
```suggestion
            すべての対象者が回答済みの場合 true を返す。それ以外は false を返す。 (対象者が存在しない場合は true を返す)
```

2023-12-10 12:07 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +          $ref: "#/components/schemas/UsersAndGroups"
```suggestion
    QuestionnaireTargetsAndAdmins:
      type: object
      properties:
        targets:
          $ref: "#/components/schemas/UsersAndGroups"
        admins:
          $ref: "#/components/schemas/UsersAndGroups"
      required:
        - targets
        - admins
```

2023-12-10 12:11 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +            ページ数
```suggestion
            合計のページ数
```

2023-12-10 12:12 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +                回答必須でない場合、またはすべてのターゲットが回答済みの場合、true を返す。それ以外はfalseを返す。
QuestionnaireAllResponded を使った方がすっきりするかもです

2023-12-10 12:13 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +              format: date-time
QuestionnaireRespondedAtを使った方がすっきりするかもです

2023-12-10 12:18 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +        自分の回答のみ取得 (true), 自分の回答以外も含めてすべて取得 (false)。デフォルトはfalse。
命名が直感的ではない気がします　onlyMyResponse や myResponseOnly あたりが直感的な気がします

2023-12-10 12:19 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +        type: boolean
isMyResponseInQueryと同じく

2023-12-10 12:19 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +        type: boolean
isMyResponseInQueryと同じく

2023-12-10 15:12 UTC, reiroop commented on docs/swagger/swagger.yaml
> +            ページ数
修正しました

2023-12-10 15:20 UTC, reiroop commented on docs/swagger/swagger.yaml
> +        type: boolean
修正しました

2023-12-10 15:20 UTC, reiroop commented on docs/swagger/swagger.yaml
> +        type: boolean
修正しました

2023-12-10 15:20 UTC, reiroop commented on docs/swagger/swagger.yaml
> +        自分の回答のみ取得 (true), 自分の回答以外も含めてすべて取得 (false)。デフォルトはfalse。
修正しました

2023-12-10 15:22 UTC, reiroop commented on docs/swagger/swagger.yaml
> +              format: date-time
修正しました

2023-12-10 15:24 UTC, reiroop commented on docs/swagger/swagger.yaml
> +        - responded_at
消します！

2023-12-10 15:56 UTC, reiroop commented on docs/swagger/swagger.yaml
> +        - $ref: "#/components/schemas/ResponseSettingsScale"
修正しました！

2023-12-10 15:56 UTC, reiroop commented on docs/swagger/swagger.yaml
> +        responseNum:
修正しました！

2023-12-10 15:57 UTC, reiroop commented on docs/swagger/swagger.yaml
> +            type: string
たぶん修正できてると思います

2023-12-10 15:57 UTC, reiroop commented on docs/swagger/swagger.yaml
> +            type: string
たぶん修正できてると思いますv2

2023-12-10 15:58 UTC, reiroop commented on docs/swagger/swagger.yaml
> +            回答必須でない場合、またはすべてのターゲットが回答済みの場合、true を返す。それ以外はfalseを返す。
修正しました

2023-12-10 15:59 UTC, reiroop commented on docs/swagger/swagger.yaml
> +          $ref: "#/components/schemas/UsersAndGroups"
修正しました

2023-12-11 07:11 UTC, reiroop commented on docs/swagger/swagger.yaml
> +        allows_multiple_responses:
修正しました

2023-12-11 07:12 UTC, reiroop commented on docs/swagger/swagger.yaml
>      post:
修正しました

2023-12-11 12:45 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +        値ごとの回答数の配列
値との紐づけがなさそうです　TextとかTextLongみたいにして良さそう

2023-12-11 12:45 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +          type: integer
全部typeプロパティがあると良さそう

2023-12-11 13:19 UTC, reiroop commented on docs/swagger/swagger.yaml
> +                回答必須でない場合、またはすべてのターゲットが回答済みの場合、true を返す。それ以外はfalseを返す。
解決しました

2023-12-11 14:18 UTC, reiroop commented on docs/swagger/swagger.yaml
> +        answerIndexes:
修正しました

2023-12-12 02:58 UTC, reiroop commented on docs/swagger/swagger.yaml
> +              type: number
修正しました

2023-12-12 02:58 UTC, reiroop commented on docs/swagger/swagger.yaml
> +          type: integer
修正しました

2023-12-12 07:09 UTC, reiroop commented on docs/swagger/swagger.yaml
> +          $ref: "#/components/schemas/QuestionType"
修正済みです

2023-12-12 07:10 UTC, reiroop commented on docs/swagger/swagger.yaml
> +              format: date-time
どうにかしました

2023-12-12 07:10 UTC, reiroop commented on docs/swagger/swagger.yaml
>          type: boolean
直し忘れてました

2023-12-12 07:11 UTC, reiroop commented on docs/swagger/swagger.yaml
>          type: boolean
直しました

2023-12-12 07:59 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +        自分に対するリマインドが有効かどうか
booleanではなく、`{status: boolean}`みたいなオブジェクトにしてほしいです

2023-12-12 13:04 UTC, reiroop commented on docs/swagger/swagger.yaml
> +        値ごとの回答数の配列
これいい感じにしました、まだ見てなければ確認お願いします

2023-12-12 13:09 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +        - indexes
```suggestion
    ResultSettingsAnswerCountPerNumber:
      type: object
      properties:
        answerCountPerNumber: #TODO: 配列なのに複数形じゃないの気になる
          type: array
          items:
            type: object
            properties:
              number:
                type: number
              answerCount:
                type: number
            required:
              - number
              - answerCount
      required:
        - answerCountPerNumber
```

2023-12-12 13:10 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +        - indexes
```suggestion
    ResultSettingsAnswerCountPerIndex:
      type: object
      properties:
        AnswerCountPerIndex: #TODO: 配列なのに複数形じゃないの気になるv2
          type: array
          items:
            type: object
            properties:
              index:
                type: number
              answerCount:
                type: number
            required:
              - index
              - answerCount
      required:
        - AnswerCountPerIndex
```

2023-12-12 13:15 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +            - maxLength
maxLengthはoptionalな方がいいかも
```suggestion
    QuestionSettingsText:
      allOf:
        - $ref: "#/components/schemas/QuestionTypeText"
        - type: object
          properties:
            maxLength:
              type: integer
```

2023-12-12 13:15 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +            - maxLength
```suggestion
    QuestionSettingsTextLong:
      allOf:
        - $ref: "#/components/schemas/QuestionTypeTextLong"
        - type: object
          properties:
            maxLength:
              type: number
```

2023-12-12 13:16 UTC, cp-20 commented on docs/swagger/swagger.yaml
> +            - maxValue
```suggestion
    QuestionSettingsNumber:
      allOf:
        - $ref: "#/components/schemas/QuestionTypeNumber"
        - type: object
          properties:
            minValue:
              type: integer
            maxValue:
              type: integer
```

2023-12-12 13:17 UTC, cp-20 commented on docs/swagger/swagger.yaml
>        type: object
```suggestion
            - minValue
            - maxValue
    NewResponse:
      type: object
```

2023-12-12 14:12 UTC, reiroop commented on docs/swagger/swagger.yaml
修正しました

2023-12-12 14:13 UTC, reiroop commented on docs/swagger/swagger.yaml
> +        自分に対するリマインドが有効かどうか
修正しました

2023-12-12 15:07 UTC, cp-20 approved these changes

2023-12-12 15:10 UTC, merged