匿名解答の追加(openapi)
traPtitech/anke-to pull request #1280
Opened 2024-11-05 07:07 UTC by kavos113

#1158 をopenapi向けに移植
middlewareが未実装です

2024-11-09 00:40 UTC, kavos113 commented
openapiのスキーマ変更に合わせて修正しました

2024-12-01 05:28 UTC, kaitoyama requested changes
遅れてすみません。一点だけ追加仕様に対するテストの作成お願いします!

2024-12-01 05:28 UTC, kaitoyama commented on model/questionnaires_test.go
> +			description: "update is_anonymous(false->true)",
これ、true->falseに対してエラーが発生するっていうtestが欲しいですね

2024-12-02 12:58 UTC, kaitoyama commented on model/questionnaires_test.go
> +			description: "update is_anonymous(false->true)",
あー、そっかー、であればcontrollerにおいおいテスト追加するとかで対応ですかね。(ほかのビジネスロジックもcontrollerにありそうなので)

2024-12-02 12:59 UTC, kaitoyama commented
あとでconflict直します

2024-12-04 12:57 UTC, merged