GET /results/:questionnaireIDの認証をmiddlewareに
traPtitech/anke-to pull request #600
Opened 2021-09-11 13:59 UTC by MotoyaAsahina

fix #344 
レビューお願いします:pray:

2021-09-12 01:16 UTC, mazrean commented
テストに落ちているのは今まで認証系をGET /results/:questionnaireIDでやっていたときに認証のテストも入っていたので、それに落ちてしまっているからです。
GET /results/:questionnaireIDの認証チェック系のテストケースとそれ用のmock(あれば)を削ってしまって良いです。
余裕があればで良いですが、今回追加したmiddlewareにテストをつけてもらえるとありがたいです。

2021-09-12 01:31 UTC, mazrean requested changes
実装は完璧。
ただ、いくつか元実装に良くない点があって、それを今回Middlewareに認証を移すタイミングで直してしまいたいので、その辺りの修正をお願いしたいです:pray:
あと、↑で書いたテスト関連の話も確認お願いします。

2021-09-12 01:31 UTC, mazrean commented on router/middleware.go
> +			c.Logger().Error(err)
(元実装がよくないのですが)ここは`c.Logger().Info(err)`にして欲しいです:pray:

2021-09-12 01:31 UTC, mazrean commented on router/middleware.go
> +					return err
ここも元の実装が悪いのですが、anke-toが使っているechoというライブラリでは`echo.HTTPError`型のエラーを返すと勝手にエラーのレスポンスを返してくれます。
参考: https://echo.labstack.com/guide/error-handling/
エラーハンドリングはできる限りこれに乗って行いたいので`return echo.NewHTTPError(~)`のように変えて欲しいです。
HTTPのStatusCodeは想定外のエラー発生なので500 InternalServerErrorが良さそう。

2021-09-12 01:31 UTC, mazrean commented on router/middleware.go
> +				return echo.NewHTTPError(http.StatusNotFound, err)
ここも元実装の良くない点なのですが、ResultAuthenticate内の他の場所も含めてエラーを返す前に適切なlog levelでエラーを返して欲しいです。
500 InternalServerErrorは基本想定外のエラーで本番環境で発生したらわかるようにしたいので`c.Logger().Error(err)`、それ以外は大体`c.Logger().Info(err)`で良いと思います。
`fmt.Errorf(err)`で包んだりしてエラーの発生箇所までわかるように出来ているとベスト。

2021-09-12 14:41 UTC, MotoyaAsahina commented on router/middleware.go
> +				return echo.NewHTTPError(http.StatusNotFound, err)
修正で、`fmt.Errorf(err)`で包んでエラーの発生箇所がわかるようになってるでしょうか。

2021-09-13 01:30 UTC, MotoyaAsahina commented
修正で、`fmt.Errorf(err)`で包んでエラーの発生箇所がわかるようになってるでしょうか。

2021-09-14 12:26 UTC, mazrean reviewed
result_test.goの修正で、middlewareの設定をするという形で修正していると思うのですが、できればResultAuthenticateはResultAuthenticate、GetResultsはGetResultsでテストをする形にしたいので、results_test.goから認証関係のテストを消して、ResultAuthenticateに対して新しいテストを追加して欲しいです:pray:

2021-09-14 12:32 UTC, mazrean requested changes
レビューで書き忘れていたので追記。
`fmt.Errorf`使うのは元のエラーの情報を保ちつつエラーメッセージに新しい文字を追加できて、どこでエラーが発生したか分かりやすくなるのでとても良いです。

2021-09-14 12:32 UTC, mazrean commented on router/middleware.go
> +				return echo.NewHTTPError(http.StatusNotFound, fmt.Errorf("resShared of questionnaireID:%d not found (error: %w)", questionnaireID, err))
`fmt.Errorf`で返しているの:+1:
ただ、説明しなかった自分が悪いのですが、エラーということが明確にわかるように、エラーメッセージは`failed to ~:%w`のような形式で揃えているので、できればその形に揃えて欲しいです。

2021-09-17 07:33 UTC, mazrean approved these changes
LGTM!

2021-09-17 07:33 UTC, merged