Post /responses のvalidator設定
traPtitech/anke-to pull request #643
Opened 2021-09-26 17:00 UTC by xxarupakaxx

Close https://github.com/traPtitech/anke-to/issues/597

2021-09-27 03:39 UTC, mazrean requested changes
Responsesへのバリデーション設定としては悪くないと思います。
ただ、テストにちょっと良くないところがあるので修正お願いします。

2021-09-27 03:39 UTC, mazrean commented on router/responses.go
> +	Body        []model.ResponseBody `json:"body" validate:"required"`
このPRでmodel.ResponseBodyにvalidateタグつけるぐらいまではやって良さそう

2021-09-27 03:39 UTC, mazrean commented on router/responses_test.go
> +			description: "旧クライアントの一般的なリクエストなのでエラーなし",
これだと
>旧クライアントの一般的なリクエスト

ではないかな。
テストの最初の確実に通るであろうケースを最初のテストケースには置いて欲しくて、
`QuestionID`は0とかの特殊な値ではないやつ(`1`とか)みたいなのを入れて、他のケースでそれを1項目ずつ変えることで項目を1つずつチェックしていく、みたいにして欲しい

2021-09-27 03:39 UTC, mazrean commented on router/responses_test.go
> +						QuestionID:     1,
同時に2つ以上のことを変えるとどっちが原因で落ちたのか分からなくてテストが落ちた時に困るのでここのQuestionIDはQuestionIDは変えない方が良い

2021-09-27 03:39 UTC, mazrean commented on router/responses_test.go
> +				ID:          2,
Bodyををnilにするなら、ここもIDは変えない方が良い

2021-09-27 03:41 UTC, mazrean reviewed
書き忘れていたことがあったので追加しました

2021-09-27 03:41 UTC, mazrean commented on router/responses_test.go
> +/*func TestPostResponse(t *testing.T) {
ここってなぜコメントアウトしているの？

2021-09-27 06:53 UTC, xxarupakaxx commented on router/responses_test.go
> +/*func TestPostResponse(t *testing.T) {
questions_test.goとかにValidationのテストのみ書かれていたので使わない方針なのかな～って思っちゃいました...元に戻しておきます

2021-09-27 14:31 UTC, xxarupakaxx commented
Lintのエラーが出た場合、すべきコマンドって何ですか？
`golandci-lint run`を使ったらいろんなファイルからエラーがでてきてどうすればいいか悩んでいます..

2021-09-27 14:33 UTC, mazrean commented
Github Actionsのgolangciのところ(https://github.com/traPtitech/anke-to/pull/643/checks?check_run_id=3717645046)を見ると原因が分かります

2021-09-27 16:11 UTC, xxarupakaxx commented
このコンフリクトはいったんマージコマンド叩いて解消させるという方法がいいんでしょうか

2021-09-27 19:34 UTC, mazrean commented
今回は自分のmasterに入れた変更が原因だったのでこちらで解消してしまいました
正直解消できればどの方法でも良いですが、個人的にはrebaseでmasterを取り込む方法が好きです

2021-09-28 03:39 UTC, xxarupakaxx commented
Cl/testのエラー文で
`{"time":"2021-09-28T12:08:01.832225077+09:00","level":"ERROR","prefix":"echo","file":"responses.go","line":"59","message":"failed to get validator: failed to get validator"}`
 があったので`getValidator(c)`にエラーが出たことはわかりますが、ほかの`quetions.go`や`guetionaires.go`ではエラーが出ないがわかりません
responses.goだけエラーが出ているのでresponses_test.goの書き方が間違っていると思いましたが、書き方は同じだったのでエラーの詳細を見つけることが難しくてどうすればいいでしょうか

2021-09-28 04:36 UTC, mazrean commented
`getValidator`の中(https://github.com/traPtitech/anke-to/blob/master/router/middleware.go#L336-L342 )でやっていることは分かりますか？

2021-09-28 04:38 UTC, mazrean commented
ヒント: https://github.com/labstack/echo/blob/master/context.go#L99-L103

2021-09-28 05:57 UTC, mazrean commented
それであっています

2021-09-28 06:19 UTC, xxarupakaxx commented
あとはテストを修正するべきなのはわかるんですが、`TestPostResponseValidate`で`isErr`がtrueであるエラーのテストケースの`err`がnilである理由を探していて`err := validate.Struct(test.request)`の部分でしっかりとエラーを返すところが通ってしまいerrがnilになってしまったと予想していますが、validatorがうまく機能しなくてよくわからず状態です..

2021-09-28 06:55 UTC, mazrean commented
よく見るとエラーになるはずなのにエラーになっていない項目は全てBodyの要素のバリデーションのチェックなのがわかると思います。
それを踏まえるとある程度検討がつきそう。

2021-09-28 08:00 UTC, xxarupakaxx commented
つまり`/model`にはvalidation設定が働いていないということですね..

2021-09-28 08:07 UTC, xxarupakaxx commented
https://pkg.go.dev/github.com/go-playground/validator/v10@v10.9.0#Validate.Struct
しかし`model.ResopnseBody`のフィールドは公開されているので`validate.Struct`で読み取られているはずなんですが、エラーを返さないとなるとどこが原因かわからず。

2021-09-28 08:10 UTC, mazrean commented
https://pkg.go.dev/github.com/go-playground/validator/v10@v10.9.0#Validate.Struct
にスライスの各要素のチェックまですると書いてありますか？

2021-09-28 08:13 UTC, mazrean commented
正解を言うと、diveをつけないとgo-playground/validatorはスライスの各要素を確認してくれないようです。
自分はググってみて、(特に直接的に書かれているわけではないですが)
https://github.com/cisco-system-traffic-generator/trex-emu/issues/4
を見て、「diveないとチェックしてくれなさそうだなぁ」と思い、つけたらテスト通るようになりました。

2021-09-28 08:13 UTC, xxarupakaxx commented
validateタグに`dive`を追加するとうまくいきそうな感じがします

2021-09-28 09:38 UTC, xxarupakaxx commented
```
=== RUN   TestQuestionnaires/GetResponseReadPrivilegeInfoByQuestionnaireID
=== PAUSE TestQuestionnaires/GetResponseReadPrivilegeInfoByQuestionnaireID
=== CONT  TestQuestions/GetQuestions
    questions_test.go:40: 
        	Error Trace:	questions_test.go:894
        	Error:      	Should be true
        	Test:       	TestQuestions/GetQuestions
        	Messages:   	questionID: valid%!(EXTRA string=sort)
=== CONT  TestQuestions/CheckQuestionAdmin
```
で`questions_test.go`をいじってないのでなぜエラーが出ているかわかりません。エラー文はtrueであるべきと書かれているがどこをどう直せばいいのか..

2021-09-28 10:06 UTC, mazrean commented
これなので何回か回してみてください:pray:
https://github.com/traPtitech/anke-to/issues/577

2021-09-28 11:05 UTC, xxarupakaxx commented
10回回してみたんですが、うまくいかず...
エラー文を何回か確認するが出る箇所が異なる。。

2021-09-28 12:31 UTC, mazrean requested changes

2021-09-28 12:31 UTC, mazrean commented on router/responses_test.go
> +			description: "TextタイプでoptionResponseが50文字以上でエラー",
50文字以上でエラーのチェックだけだと49文字以上でエラーになっていても通ってしまうので50文字ぴったりで通るのも確認して欲しいです(他の場所も同様)

2021-09-28 13:05 UTC, mazrean approved these changes
LGTM!

2021-09-28 13:06 UTC, merged