WIP: クエリパラメータにvalidation設定をする
traPtitech/anke-to pull request #666
Opened 2021-09-29 06:55 UTC by xxarupakaxx

`GET /questionnaires`のクエリパラメータにvalidationを付けてみました.
そしてテストケースをいくつか作成し通ったのでPRを出しました
ほかのところにもクエリパラメータがあるので一応WIPで出します

2021-09-29 07:09 UTC, xxarupakaxx commented
クエリパラメータのJSONの扱いってどうなるんですか？
`GetQuestionnairesQueryParam`の構造体のjsonタグは必要ないのでしょうか？

2021-09-29 07:17 UTC, mazrean commented
jsonタグは必要ないです。
というのも、goplayground validatorはjsonのvaludateをするのではなく構造体のバリデーションをしているのでクエリパラメーターがjsonになることはないからです。

2021-09-29 16:08 UTC, xxarupakaxx commented
traQIDってクエリパラメータじゃないですね....外してテストも修正します

2021-09-30 00:54 UTC, mazrean requested changes
大体OKです。
ただ、テストに甘い部分があるので修正お願いします。

2021-09-30 00:54 UTC, mazrean commented on router/questionnaires_test.go
> +			description: "一般的なQueryParameterなので空文字にしてもエラーなし",
各要素ごとに空文字でも大丈夫かチェックしたほうが丁寧で良いです

2021-09-30 00:54 UTC, mazrean commented on router/questionnaires_test.go
> +	tests := []struct {
sortはcreated_at、-created_at、title、-title、modified_at、-modified_atの全てで大丈夫かチェックした方が良いです

2021-09-30 00:54 UTC, mazrean commented on router/questionnaires_test.go
> +	tests := []struct {
念の為Nontargetedがfalseでも大丈夫かチェックした方が良さそう

2021-09-30 00:54 UTC, mazrean commented on router/questionnaires.go
> +	validate,err := getValidator(c)
validateはintへの変換などの前に置かないと意味がないので、変換前にして欲しいです

2021-09-30 00:54 UTC, mazrean commented on router/users_test.go
> +	tests := []struct{
こちらもSortがcreated_at、-created_at、title、-title、modified_at、-modified_atのどれでも大丈夫か、
Answerdがanswerd、unansweredのどちらでも大丈夫かチェックして欲しいです

2021-09-30 00:54 UTC, mazrean commented on router/users_test.go
> +			description: "一般的なQueryParameterなのでエラーなし",
こちらも各要素ごとに空文字でも大丈夫かチェックしたほうが丁寧で良いです

2021-09-30 02:20 UTC, mazrean approved these changes
go fmtしていなさそうなので、それだけしたらマージして大丈夫です

2021-09-30 03:53 UTC, merged