POST /questions を POST /questionnaires/{questionnaireID}/questionsに
traPtitech/anke-to pull request #712
Opened 2021-11-06 17:43 UTC by xxarupakaxx

ref : #386 

まだテストが足りませんがPRを出しました

主な変更点として
- endpointの変更
- テストの追加
- Swaggerの修正

2021-11-09 15:22 UTC, xxarupakaxx commented
Coverできていない箇所である
 - getValidator
 - regexpの正規表現チェック
 - questionnaireIDの整数値かどうか

のテストの作り方を模索中ですが、それ以外のテストケースは追加した

2021-11-11 18:25 UTC, xxarupakaxx commented
正規表現以外のテストは:kan:

2021-11-12 04:51 UTC, xxarupakaxx commented
正規表現のテスト:kan:

2021-11-13 12:49 UTC, mazrean requested changes
大体OKだけど、POSTの場合requestBodyのquestionnaireIDはいらないので消してほしい

2021-11-13 12:49 UTC, mazrean commented on router/questions.go
>  	QuestionnaireID int      `json:"questionnaireID" validate:"min=0"`
ここ、POSTの場合いらなくなっていそうなので、うまくPOSTの場合はなくて良いようにしてほしい

2021-11-17 12:12 UTC, mazrean approved these changes
LGTM!

2021-11-17 12:17 UTC, merged