ログ追加とログレベル修正
traPtitech/anke-to pull request #748
Opened 2021-11-30 08:50 UTC by MotoyaAsahina

Close #598

2021-12-02 06:25 UTC, xxarupakaxx requested changes
少しだけ:pray:

2021-12-02 06:25 UTC, xxarupakaxx commented on router/questionnaires.go
> +		c.Logger().Info(fmt.Errorf("failed to convert page to int:%w", err))
`c.logger.infof`を使えばよさそう

2021-12-02 06:25 UTC, xxarupakaxx commented on router/questionnaires.go
> +		c.Logger().Error(err)
`users.go`と`responses.go`も統一してほしいです

2021-12-02 06:25 UTC, xxarupakaxx commented on router/questionnaires.go
> +		c.Logger().Error(err)
同じように`getValidator`を使っている箇所があるはず

2021-12-02 06:27 UTC, xxarupakaxx commented
カバーされていないテストも書いてほしいけど変更しているファイルが多いからどうしようかと悩み
(ハッカソン期間中にテスト書き書き終わってくれれば僕とマズリーンさんはいじらないと思うのでやってもよさそう..?)

2021-12-02 06:42 UTC, mazrean commented
テストはやるとしたら別PRの方が良さそう(内容的に別なので)

2021-12-02 06:45 UTC, xxarupakaxx commented
確かにそうですね..

2021-12-02 06:50 UTC, mazrean reviewed
少し気になったところ追記しておきました

2021-12-02 06:50 UTC, mazrean commented on router/questionnaires.go
> +		c.Logger().Error(err)
Errorfとかでどこで発生したか区別できるようにしたほうが良さそう(Errorは予期しないエラーが発生した時なので、「何かバグが発生した時にどういうログがみたいか」を考えてみるとよかったりする)

2021-12-02 06:50 UTC, mazrean commented on router/questionnaires.go
> +		c.Logger().Info(fmt.Errorf("page must be greater than 0"))
ここはただ文字列をログ吐いているだけなので、Infoのままで`"page must be greater than 0"`をそのまま引数で渡せば良さそう

2021-12-02 06:50 UTC, mazrean commented on router/questionnaires.go
> +		c.Logger().Error(err)
他のerrそのまま渡している箇所も同様

2021-12-02 06:50 UTC, mazrean commented on router/questionnaires.go
> +		c.Logger().Errorf("failed to create a questionnaire: %w", err)
Errorfって`%w`使えたっけ？(使えなかった気がしているけど記憶違いかもしれない)

2021-12-02 07:12 UTC, xxarupakaxx commented on router/questionnaires.go
> +		c.Logger().Errorf("failed to create a questionnaire: %w", err)
使えないですね.(make testでログみて、そのあと`%v`にしたらうまくエラー文が表示された)

2021-12-02 07:21 UTC, MotoyaAsahina commented on router/questionnaires.go
> +		c.Logger().Errorf("failed to create a questionnaire: %w", err)
自分も確認しました。fmt.Errorfを書くではなくて、%vを使うで良いですか？

2021-12-02 07:53 UTC, xxarupakaxx commented on router/questionnaires.go
> +		c.Logger().Errorf("failed to create a questionnaire: %w", err)
それでいいと思います！

2021-12-04 02:20 UTC, xxarupakaxx approved these changes

2021-12-05 23:35 UTC, merged